//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaarWorld.Resources.Raw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SaarResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaarResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaarWorld.Resources.Raw.SaarResources", typeof(SaarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air freight.
        /// </summary>
        internal static string AIR_FREIGHT {
            get {
                return ResourceManager.GetString("AIR_FREIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string BACK_TO_HOME {
            get {
                return ResourceManager.GetString("BACK_TO_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Company.
        /// </summary>
        internal static string CALL_COMPANY {
            get {
                return ResourceManager.GetString("CALL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel order.
        /// </summary>
        internal static string CANCEL_ORDER {
            get {
                return ResourceManager.GetString("CANCEL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string CARGO {
            get {
                return ResourceManager.GetString("CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Choose cargo.
        /// </summary>
        internal static string CHOOSE_CARGO {
            get {
                return ResourceManager.GetString("CHOOSE_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance.
        /// </summary>
        internal static string CLEARANCE {
            get {
                return ResourceManager.GetString("CLEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string COMPANIES {
            get {
                return ResourceManager.GetString("COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that the Package has arrived.
        /// </summary>
        internal static string CONFIRM_THAT_THE_PACKAGE_HAS_ARRIVED {
            get {
                return ResourceManager.GetString("CONFIRM_THAT_THE_PACKAGE_HAS_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        internal static string CURRENT_LOCATION_PAGE {
            get {
                return ResourceManager.GetString("CURRENT_LOCATION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery details.
        /// </summary>
        internal static string DELIVERY_DETAILS {
            get {
                return ResourceManager.GetString("DELIVERY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery location .
        /// </summary>
        internal static string DELIVERY_LOCATION {
            get {
                return ResourceManager.GetString("DELIVERY_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery recieved.
        /// </summary>
        internal static string DELIVERY_RECIEVED {
            get {
                return ResourceManager.GetString("DELIVERY_RECIEVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the Shipment .
        /// </summary>
        internal static string DESCRIBE_THE_SHIPMENT {
            get {
                return ResourceManager.GetString("DESCRIBE_THE_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string DIRECTIONS {
            get {
                return ResourceManager.GetString("DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        internal static string DISTANCE {
            get {
                return ResourceManager.GetString("DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        internal static string EDIT_ACCOUNT {
            get {
                return ResourceManager.GetString("EDIT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email....
        /// </summary>
        internal static string EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("EMAIL_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new safe password please!.
        /// </summary>
        internal static string ENTER_A_NEW_SAFE_PASSWORD_PLEASE_ {
            get {
                return ResourceManager.GetString("ENTER A NEW SAFE PASSWORD PLEASE!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password ?.
        /// </summary>
        internal static string FORGET_PASSWORD {
            get {
                return ResourceManager.GetString("FORGET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am moving my home....
        /// </summary>
        internal static string I_AM_MOVING_MY_HOME___ {
            get {
                return ResourceManager.GetString("I_AM_MOVING_MY_HOME...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s3 Meters *3 Meters And Weight 5Kg....
        /// </summary>
        internal static string IT_S_A_3_METERS___METERS_AND_WEIGHT_5KG___ {
            get {
                return ResourceManager.GetString("IT\'S_A_3_METERS_*_METERS_AND_WEIGHT_5KG...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name....
        /// </summary>
        internal static string NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("NAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NOTIFICATIONS {
            get {
                return ResourceManager.GetString("NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string ORDER_DETAILS_PAGE {
            get {
                return ResourceManager.GetString("ORDER_DETAILS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ORDER_QR_CONFIRMATION {
            get {
                return ResourceManager.GetString("ORDER_QR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string ORDERS {
            get {
                return ResourceManager.GetString("ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package location .
        /// </summary>
        internal static string PACKAGE_LOCATION {
            get {
                return ResourceManager.GetString("PACKAGE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password....
        /// </summary>
        internal static string PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string PASSWORD_RESET {
            get {
                return ResourceManager.GetString("PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PHONENUMBER {
            get {
                return ResourceManager.GetString("PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number....
        /// </summary>
        internal static string PHONENUMBER_PLACEHOLDER {
            get {
                return ResourceManager.GetString("PHONENUMBER_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order Now.
        /// </summary>
        internal static string PLACE_ORDER_NOW {
            get {
                return ResourceManager.GetString("PLACE_ORDER_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please check your email,we have sent you a 6 digits number for verification.
        /// </summary>
        internal static string PLEASE_CHECK_YOUR_EMAIL_WE_HAVE_SENT_YOU_A_6_DIGITS_NUMBER_FOR_VERIFICATION {
            get {
                return ResourceManager.GetString("PLEASE CHECK YOUR EMAIL,WE HAVE SENT YOU A 6 DIGITS NUMBER FOR VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new account.
        /// </summary>
        internal static string REGISTER_A_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("REGISTER A NEW ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate.
        /// </summary>
        internal static string RELOCATE {
            get {
                return ResourceManager.GetString("RELOCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password....
        /// </summary>
        internal static string REPEATPASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("REPEATPASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatPassword.
        /// </summary>
        internal static string RPEATPASSWORD {
            get {
                return ResourceManager.GetString("RPEATPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srea freight.
        /// </summary>
        internal static string SEA_FREIGHT {
            get {
                return ResourceManager.GetString("SEA_FREIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Send email .
        /// </summary>
        internal static string SEND_EMAIL {
            get {
                return ResourceManager.GetString("SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Start browsing our offers now.
        /// </summary>
        internal static string START_BROWSING_OUR_OFFERS_NOW {
            get {
                return ResourceManager.GetString("START_BROWSING_OUR_OFFERS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Start now .
        /// </summary>
        internal static string START_NOW {
            get {
                return ResourceManager.GetString("START NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been confirmed.
        /// </summary>
        internal static string THE_ORDER_HAS_BEEN_CONFIRMED {
            get {
                return ResourceManager.GetString("THE_ORDER_HAS_BEEN_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track the order.
        /// </summary>
        internal static string TRACK_THE_ORDER {
            get {
                return ResourceManager.GetString("TRACK_THE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two chairs,One Door,2 Boxes....
        /// </summary>
        internal static string TWO_CHARIRS___ONE_DOOR___2___BOXES___ {
            get {
                return ResourceManager.GetString("TWO_CHARIRS_,_ONE_DOOR_;_2_;_BOXES...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username....
        /// </summary>
        internal static string USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string VERIFY {
            get {
                return ResourceManager.GetString("VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you going to move ?.
        /// </summary>
        internal static string WHAT_ARE_YOU_GOING_TO_MOVE {
            get {
                return ResourceManager.GetString("WHAT_ARE_YOU_GOING_TO_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the size of the shipment ?.
        /// </summary>
        internal static string WHAT_IS_THE_SIZE_OF_THE_SHIPMENT {
            get {
                return ResourceManager.GetString("WHAT_IS_THE_SIZE_OF_THE_SHIPMENT", resourceCulture);
            }
        }
    }
}
