//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaarWorld.Resources.Raw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SaarResources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaarResources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaarWorld.Resources.Raw.SaarResources.fr", typeof(SaarResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret aérien.
        /// </summary>
        public static string AIR_FREIGHT {
            get {
                return ResourceManager.GetString("AIR_FREIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à l&apos;accueil.
        /// </summary>
        public static string BACK_TO_HOME {
            get {
                return ResourceManager.GetString("BACK_TO_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeler la Companie.
        /// </summary>
        public static string CALL_COMPANY {
            get {
                return ResourceManager.GetString("CALL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Annuler.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler la commande.
        /// </summary>
        public static string CANCEL_ORDER {
            get {
                return ResourceManager.GetString("CANCEL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargaison.
        /// </summary>
        public static string CARGO {
            get {
                return ResourceManager.GetString("CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Choisir cargaison .
        /// </summary>
        public static string CHOOSE_CARGO {
            get {
                return ResourceManager.GetString("CHOOSE_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorisation.
        /// </summary>
        public static string CLEARANCE {
            get {
                return ResourceManager.GetString("CLEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string COMPANIES {
            get {
                return ResourceManager.GetString("COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez que le colis est arrivé.
        /// </summary>
        public static string CONFIRM_THAT_THE_PACKAGE_HAS_ARRIVED {
            get {
                return ResourceManager.GetString("CONFIRM_THAT_THE_PACKAGE_HAS_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau compte.
        /// </summary>
        public static string CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation Currente.
        /// </summary>
        public static string CURRENT_LOCATION_PAGE {
            get {
                return ResourceManager.GetString("CURRENT_LOCATION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison.
        /// </summary>
        public static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de livraison.
        /// </summary>
        public static string DELIVERY_DETAILS {
            get {
                return ResourceManager.GetString("DELIVERY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu de livraison .
        /// </summary>
        public static string DELIVERY_LOCATION {
            get {
                return ResourceManager.GetString("DELIVERY_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison reçue.
        /// </summary>
        public static string DELIVERY_RECIEVED {
            get {
                return ResourceManager.GetString("DELIVERY_RECIEVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décrire l&apos;expédition .
        /// </summary>
        public static string DESCRIBE_THE_SHIPMENT {
            get {
                return ResourceManager.GetString("DESCRIBE_THE_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string DIRECTIONS {
            get {
                return ResourceManager.GetString("DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string DISTANCE {
            get {
                return ResourceManager.GetString("DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le compte.
        /// </summary>
        public static string EDIT_ACCOUNT {
            get {
                return ResourceManager.GetString("EDIT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saisir l&apos; email....
        /// </summary>
        public static string EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("EMAIL_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez un nouveau mot de passe sécurisé s&apos;il vous plaît !.
        /// </summary>
        public static string ENTER_A_NEW_SAFE_PASSWORD_PLEASE_ {
            get {
                return ResourceManager.GetString("ENTER A NEW SAFE PASSWORD PLEASE!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string FORGET_PASSWORD {
            get {
                return ResourceManager.GetString("FORGET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez déja un compte.
        /// </summary>
        public static string HAVE_ALREADY_AN_ACCOUNT {
            get {
                return ResourceManager.GetString("HAVE ALREADY AN ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je déménage mon domicile....
        /// </summary>
        public static string I_AM_MOVING_MY_HOME___ {
            get {
                return ResourceManager.GetString("I_AM_MOVING_MY_HOME...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est 3 mètres * 3 mètres et un poids de 5 kg....
        /// </summary>
        public static string IT_S_A_3_METERS___METERS_AND_WEIGHT_5KG___ {
            get {
                return ResourceManager.GetString("IT\'S_A_3_METERS_*_METERS_AND_WEIGHT_5KG...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir le Prénom ....
        /// </summary>
        public static string NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("NAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NOTIFICATIONS {
            get {
                return ResourceManager.GetString("NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de la commande.
        /// </summary>
        public static string ORDER_DETAILS_PAGE {
            get {
                return ResourceManager.GetString("ORDER_DETAILS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ORDER_QR_CONFIRMATION {
            get {
                return ResourceManager.GetString("ORDER_QR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Commandes.
        /// </summary>
        public static string ORDERS {
            get {
                return ResourceManager.GetString("ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement du colis .
        /// </summary>
        public static string PACKAGE_LOCATION {
            get {
                return ResourceManager.GetString("PACKAGE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe ....
        /// </summary>
        public static string PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation du mot de passe.
        /// </summary>
        public static string PASSWORD_RESET {
            get {
                return ResourceManager.GetString("PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numéro de téléphone.
        /// </summary>
        public static string PHONENUMBER {
            get {
                return ResourceManager.GetString("PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numéro de téléphone....
        /// </summary>
        public static string PHONENUMBER_PLACEHOLDER {
            get {
                return ResourceManager.GetString("PHONENUMBER_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander maintenant.
        /// </summary>
        public static string PLACE_ORDER_NOW {
            get {
                return ResourceManager.GetString("PLACE_ORDER_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veulliez vérifier votre courriel, nous vous avons envoyé un numéro de 6 chiffres pour la vérification .
        /// </summary>
        public static string PLEASE_CHECK_YOUR_EMAIL_WE_HAVE_SENT_YOU_A_6_DIGITS_NUMBER_FOR_VERIFICATION {
            get {
                return ResourceManager.GetString("PLEASE CHECK YOUR EMAIL,WE HAVE SENT YOU A 6 DIGITS NUMBER FOR VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFIL.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau compte.
        /// </summary>
        public static string REGISTER_A_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("REGISTER A NEW ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déménager.
        /// </summary>
        public static string RELOCATE {
            get {
                return ResourceManager.GetString("RELOCATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le mot de passe.
        /// </summary>
        public static string REPEATPASSWORD {
            get {
                return ResourceManager.GetString("REPEATPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confimrer le mot de passe ....
        /// </summary>
        public static string REPEATPASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("REPEATPASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregister.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret maritime.
        /// </summary>
        public static string SEA_FREIGHT {
            get {
                return ResourceManager.GetString("SEA_FREIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher....
        /// </summary>
        public static string SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un email  .
        /// </summary>
        public static string SEND_EMAIL {
            get {
                return ResourceManager.GetString("SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter nos offres maintenant .
        /// </summary>
        public static string START_BROWSING_OUR_OFFERS_NOW {
            get {
                return ResourceManager.GetString("START BROWSING OUR OFFERS NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer .
        /// </summary>
        public static string START_NOW {
            get {
                return ResourceManager.GetString("START NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande a été confirmée.
        /// </summary>
        public static string THE_ORDER_HAS_BEEN_CONFIRMED {
            get {
                return ResourceManager.GetString("THE_ORDER_HAS_BEEN_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Total.
        /// </summary>
        public static string TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suivre la commande.
        /// </summary>
        public static string TRACK_THE_ORDER {
            get {
                return ResourceManager.GetString("TRACK_THE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deux chaises, une porte, 2 boîtes....
        /// </summary>
        public static string TWO_CHARIRS___ONE_DOOR___2___BOXES___ {
            get {
                return ResourceManager.GetString("TWO_CHARIRS_,_ONE_DOOR_;_2_;_BOXES...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur ....
        /// </summary>
        public static string USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("USERNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier.
        /// </summary>
        public static string VERIFY {
            get {
                return ResourceManager.GetString("VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que allez-vous déplacer ?.
        /// </summary>
        public static string WHAT_ARE_YOU_GOING_TO_MOVE {
            get {
                return ResourceManager.GetString("WHAT_ARE_YOU_GOING_TO_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle est la taille de l&apos;envoi ?.
        /// </summary>
        public static string WHAT_IS_THE_SIZE_OF_THE_SHIPMENT {
            get {
                return ResourceManager.GetString("WHAT_IS_THE_SIZE_OF_THE_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  votre compte a été créé avec succès.
        /// </summary>
        public static string YOUR_ACCOUNT_HAS_BEEN_CREATED_SUCCESSFULY {
            get {
                return ResourceManager.GetString("YOUR ACCOUNT HAS BEEN CREATED SUCCESSFULY", resourceCulture);
            }
        }
    }
}
